Resources:
  TestSaileshRDSProxy:
    Type: AWS::RDS::DBProxy
    DependsOn:
      - TestSaileshAuroraDBCluster
      - TestSaileshAuoraDBInstance
      - DBSecret
      - TestSaileshRDSProxyRole
    Properties:
      Auth: 
        - Description: "Proxy for Aurora Serverless"
          AuthScheme: SECRETS
          SecretArn: 
            Ref: DBSecret
      DBProxyName: TestSaileshRDSProxy
      EngineFamily: POSTGRESQL
      RoleArn: !GetAtt TestSaileshRDSProxyRole.Arn
      VpcSubnetIds: 
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PrivateSubnet3

      VpcSecurityGroupIds: 
        - !Ref TestSaileshDBSecurityGroup