Resources:
  DBSecret:  
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: ${self:custom.ServiceName}-DBSecret
      Description: "Password for Aurora Serverless PostgreSQL database"
      SecretString: !Sub
        - '{"username": "${Username}", "password":"${Password}"}'
        - Username: "testsailesh"
          Password: "Test2024!"